version: '3.8'
services:
    node-web-app: 
        container_name: node-web-app
        image: node-web-app
        build:
            context: .
            dockerfile: Dockerfile 
        restart: always
        ports:
            - 49160:3000